# Generated by Django 5.1.6 on 2025-02-28 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_faculty_subjects'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Class',
        ),
        migrations.RenameModel(
            old_name='Subjects',
            new_name='Subject',
        ),
    ]
